"""Ask the order data a question in English.

Sends the question to Snowflake Cortex Analyst, which translates it into SQL
against the semantic view over the marts, then runs that SQL and prints the
answer. The point is that the semantic view is the only thing Analyst sees:
the natural-language path and the SQL path share one definition of revenue,
week and customer, so they cannot drift apart.

    python cortex/ask.py "which product had the highest revenue?"

Requires the same environment variables as the loader, plus the semantic view,
which is created with:

    cd dbt_project && dbt run-operation create_semantic_view
"""

import argparse
import json
import os
import re
import sys

import requests
import snowflake.connector
from dotenv import load_dotenv

load_dotenv()

# Configuration -------------------------------------------------------------

DATABASE = os.environ.get("SNOWFLAKE_DATABASE", "FASTMARKETS")
DBT_SCHEMA = os.environ.get("SNOWFLAKE_DBT_SCHEMA", "DBT_DEV")
SEMANTIC_VIEW = f"{DATABASE}.{DBT_SCHEMA}_MARTS.SV_ORDER_SALES"

REQUIRED_ENV_VARS = (
    "SNOWFLAKE_ACCOUNT",
    "SNOWFLAKE_USER",
    "SNOWFLAKE_PASSWORD",
    "SNOWFLAKE_ROLE",
    "SNOWFLAKE_WAREHOUSE",
)

# Analyst can take a while on a cold model, and a hung request in an
# orchestrator is worse than a failed one.
ANALYST_TIMEOUT = (10, 120)


def get_connection() -> snowflake.connector.SnowflakeConnection:
    missing = [name for name in REQUIRED_ENV_VARS if not os.environ.get(name)]
    if missing:
        raise RuntimeError("Missing environment variables: " + ", ".join(missing))

    return snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"],
        user=os.environ["SNOWFLAKE_USER"],
        password=os.environ["SNOWFLAKE_PASSWORD"],
        role=os.environ["SNOWFLAKE_ROLE"],
        warehouse=os.environ["SNOWFLAKE_WAREHOUSE"],
        database=DATABASE,
        login_timeout=30,
    )


def ask_analyst(conn, question: str) -> tuple[str, str]:
    """Return (interpretation, sql) for a question.

    Analyst restates the question as it understood it before answering. That
    restatement is the most useful part of the response: it is where you see
    the model has read "top seller" as revenue rather than units, and it is
    cheaper to check than the SQL.
    """
    response = requests.post(
        f"https://{conn.host}/api/v2/cortex/analyst/message",
        json={
            "messages": [
                {"role": "user", "content": [{"type": "text", "text": question}]}
            ],
            "semantic_view": SEMANTIC_VIEW,
        },
        headers={
            "Authorization": f'Snowflake Token="{conn.rest.token}"',
            "Content-Type": "application/json",
        },
        timeout=ANALYST_TIMEOUT,
    )
    if response.status_code != 200:
        raise RuntimeError(
            f"Cortex Analyst returned {response.status_code}: {response.text[:300]}"
        )

    content = response.json()["message"]["content"]
    interpretation = next(
        (part["text"] for part in content if part["type"] == "text"), ""
    )
    # Analyst prefixes the restatement with boilerplate; the restatement itself
    # is the useful part.
    interpretation = interpretation.replace(
        "This is our interpretation of your question:", ""
    )
    sql = next((part["statement"] for part in content if part["type"] == "sql"), None)
    if sql is None:
        # Analyst answers some questions in prose, for instance when it needs a
        # clarification. There is no SQL to run in that case.
        raise RuntimeError(f"No SQL in the response. Analyst said: {interpretation}")

    return interpretation.strip(), sql


def run_sql(conn, sql: str) -> tuple[list[str], list[tuple]]:
    # Analyst appends a request_id comment and a trailing semicolon, neither of
    # which the connector wants in a single-statement execute.
    cleaned = sql.split("-- Generated by Cortex Analyst")[0].strip().rstrip(";")
    cursor = conn.cursor()
    try:
        cursor.execute(cleaned)
        return [d[0] for d in cursor.description], cursor.fetchall()
    finally:
        cursor.close()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Ask the order data a question in natural language."
    )
    parser.add_argument("question", help="The question, in English.")
    parser.add_argument(
        "--show-sql",
        action="store_true",
        help="Print the SQL Analyst generated before running it.",
    )
    args = parser.parse_args(argv)

    try:
        conn = get_connection()
    except Exception as exc:
        print(f"Could not connect: {exc}", file=sys.stderr)
        return 1

    try:
        interpretation, sql = ask_analyst(conn, args.question)
        print(f"\nQuestion:       {args.question}")
        print(f"Understood as:  {re.sub(r'\\s+', ' ', interpretation)}")
        if args.show_sql:
            print(f"\nSQL:\n{sql}")

        columns, rows = run_sql(conn, sql)
        print(f"\n{' | '.join(columns)}")
        print("-" * (sum(len(c) for c in columns) + 3 * len(columns)))
        for row in rows:
            print(" | ".join(str(value) for value in row))
        print()
    except Exception as exc:
        print(f"Failed: {exc}", file=sys.stderr)
        return 1
    finally:
        conn.close()

    return 0


if __name__ == "__main__":
    sys.exit(main())
