"""Unit tests for the natural-language query CLI.

Only the pure logic is tested here: how the Analyst response is parsed and how
its SQL is cleaned before execution. The Analyst call itself is a live LLM
service - mocking it would assert that a fake returns what the fake was told
to return, which proves nothing. What is worth testing is the handling of
responses, including the shapes that are easy to get wrong: a reply with no
SQL, and the request_id comment Analyst appends to every statement.

    pytest cortex/tests -q
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import ask  # noqa: E402


class FakeResponse:
    def __init__(self, payload, status_code=200, text=""):
        self._payload = payload
        self.status_code = status_code
        self.text = text or str(payload)

    def json(self):
        return self._payload


class FakeConnection:
    host = "example.snowflakecomputing.com"

    class rest:  # noqa: N801 - mirrors the connector's attribute name
        token = "fake-token"


def _reply(text=None, sql=None):
    content = []
    if text is not None:
        content.append({"type": "text", "text": text})
    if sql is not None:
        content.append({"type": "sql", "statement": sql})
    return {"message": {"role": "analyst", "content": content}}


@pytest.fixture
def respond(monkeypatch):
    def _respond(payload, status_code=200, text=""):
        monkeypatch.setattr(
            ask.requests,
            "post",
            lambda *a, **k: FakeResponse(payload, status_code, text),
        )

    return _respond


def test_interpretation_and_sql_are_returned(respond):
    respond(_reply("How I read it", "SELECT 1"))
    interpretation, sql = ask.ask_analyst(FakeConnection(), "a question")
    assert interpretation == "How I read it"
    assert sql == "SELECT 1"


def test_boilerplate_prefix_is_stripped(respond):
    """Analyst prefixes every restatement; the restatement is the useful part."""
    respond(
        _reply(
            "This is our interpretation of your question:\n\nRevenue by product?",
            "SELECT 1",
        )
    )
    interpretation, _ = ask.ask_analyst(FakeConnection(), "q")
    assert "interpretation of your question" not in interpretation
    assert "Revenue by product?" in interpretation


def test_a_reply_without_sql_raises_and_quotes_analyst(respond):
    """Analyst answers in prose when it needs a clarification."""
    respond(_reply("Which year did you mean?", None))
    with pytest.raises(RuntimeError, match="Which year did you mean"):
        ask.ask_analyst(FakeConnection(), "revenue")


def test_http_error_is_raised_with_the_status(respond):
    respond({}, status_code=403, text="not authorised")
    with pytest.raises(RuntimeError, match="403"):
        ask.ask_analyst(FakeConnection(), "q")


class RecordingCursor:
    def __init__(self, journal):
        self.journal = journal
        self.description = [("TOTAL_REVENUE",), ("PRODUCT_NAME",)]

    def execute(self, sql):
        self.journal.append(sql)

    def fetchall(self):
        return [(149100.00, "Gadget")]

    def close(self):
        self.journal.append("CLOSED")


class RecordingConnection(FakeConnection):
    def __init__(self):
        self.journal = []

    def cursor(self):
        return RecordingCursor(self.journal)


def test_request_id_comment_and_semicolon_are_stripped():
    """Analyst appends both, and the connector rejects them in one execute."""
    conn = RecordingConnection()
    ask.run_sql(
        conn,
        "SELECT 1\n -- Generated by Cortex Analyst (request_id: abc-123)\n;",
    )
    assert conn.journal[0] == "SELECT 1"


def test_columns_and_rows_are_returned():
    conn = RecordingConnection()
    columns, rows = ask.run_sql(conn, "SELECT 1")
    assert columns == ["TOTAL_REVENUE", "PRODUCT_NAME"]
    assert rows == [(149100.00, "Gadget")]


def test_the_cursor_is_always_closed():
    conn = RecordingConnection()
    ask.run_sql(conn, "SELECT 1")
    assert conn.journal[-1] == "CLOSED"
